//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.13 at 12:26:12 PM PDT 
//


package net.feem.koom.world.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.feem.koom.world.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.feem.koom.world.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthType }
     * 
     */
    public AuthType createAuthType() {
        return new AuthType();
    }

    /**
     * Create an instance of {@link World }
     * 
     */
    public World createWorld() {
        return new World();
    }

    /**
     * Create an instance of {@link ExtraInfoType }
     * 
     */
    public ExtraInfoType createExtraInfoType() {
        return new ExtraInfoType();
    }

    /**
     * Create an instance of {@link EncryptedType }
     * 
     */
    public EncryptedType createEncryptedType() {
        return new EncryptedType();
    }

    /**
     * Create an instance of {@link BasicInfoType }
     * 
     */
    public BasicInfoType createBasicInfoType() {
        return new BasicInfoType();
    }

}
